/**
 * @enkerli/proggen — ProgGenie's progression engine, promoted from
 * apps/progression-studio (plan §6 E3 / docs/HEADLESS.md). Generation over
 * corpus transition statistics + realization through @enkerli/theory +
 * curation weighting. Framework-agnostic (localStorage access is optional-
 * chained), so it runs headless in node — the reason for the promotion, which
 * unlocks `enkerli generate`.
 *
 * The derived statistics tables ship with the package (data/transitions.json,
 * data/trigrams.json — regenerated by @enkerli/corpus-tools; the source corpus
 * is never published, per HANDOFF §5). Generation functions take a table as a
 * parameter, so importing this module pulls in no data by itself.
 */
export * from "./generate.js";
export * from "./curation.js";
