#!/usr/bin/env node
// Self-host the suite's four OFL families (Inter Tight, JetBrains Mono, Domine,
// Caveat) so every app — and Vane's plugin WebView, which can't reach a CDN —
// renders the designed type offline. Parses a Google Fonts css2 (woff2)
// response, keeps only the latin + latin-ext subsets, downloads each face
// locally, and emits fonts.css pointing at the bundled files.
//   node gen-fonts.mjs <input.css>
import { readFileSync, writeFileSync } from 'node:fs';
import { execFileSync } from 'node:child_process';

const css = readFileSync(process.argv[2], 'utf8');
const KEEP = new Set(['latin']);
const slug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');

// Split into (subset-comment, @font-face) pairs.
const blocks = [...css.matchAll(/\/\*\s*([\w-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g)];
const faces = [];
for (const [, subset, face] of blocks) {
  if (!KEEP.has(subset)) continue;
  const fam = /font-family:\s*'([^']+)'/.exec(face)[1];
  const weight = /font-weight:\s*(\d+)/.exec(face)[1];
  const style = /font-style:\s*(\w+)/.exec(face)[1];
  const url = /url\((https:\/\/[^)]+\.woff2)\)/.exec(face)[1];
  const range = /unicode-range:\s*([^;]+);/.exec(face)?.[1]?.trim();
  const file = `${slug(fam)}-${weight}${style === 'italic' ? 'i' : ''}-${subset}.woff2`;
  faces.push({ fam, weight, style, url, range, subset, file });
}

let total = 0;
for (const f of faces) {
  execFileSync('curl', ['-sSL', '-m', '30', '-o', f.file, f.url]);
  total++;
}

const out = `/* Self-hosted suite fonts — Inter Tight · JetBrains Mono · Domine, all
   SIL OFL 1.1. Generated by gen-fonts.mjs from Google Fonts (latin subset,
   woff2). Import '@enkerli/ui/fonts.css' to give
   an app the designed type offline — no CDN, so it works under a strict CSP
   and in the plugin WebView. The families match the --es-font-* stacks in
   tokens.css. */
${faces.map((f) => `@font-face {
  font-family: '${f.fam}';
  font-style: ${f.style};
  font-weight: ${f.weight};
  font-display: swap;
  src: url('./fonts/${f.file}') format('woff2');${f.range ? `\n  unicode-range: ${f.range};` : ''}
}`).join('\n')}
`;
writeFileSync('../fonts.css', out);
console.log(`downloaded ${total} faces; wrote packages/ui/fonts.css`);
